### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true # automatically start the local network container, if not already running

[[development.accounts]]
name = "me" # Required. Keys for this account will be saved to `./.stellar/identity`
default = true # Optional. Whether to use this account as the `--source` for commands that need one.

[development.contracts]
# Deploy in dependency order
usdc_mock = { 
    client = true, 
    constructor_args = "--admin me --initial_supply 1000000000000000" 
}

mock_rwa_token = { 
    client = true, 
    constructor_args = "--admin me --manager me --initial_supply 1000000000000000000" 
}

strwa_token = { 
    client = true, 
    constructor_args = "--admin me" 
}

rwa_vault = { 
    client = true, 
    constructor_args = """
    --admin me
    --rwa_token $(stellar contract id asset --asset native)
    --strwa_token $(stellar contract id asset --asset native)
    """ 
}

mock_oracle = { 
    client = true, 
    constructor_args = "--bot_address me" 
}

lending_pool = { 
    client = true, 
    constructor_args = """
    --admin me
    --oracle $(stellar contract id asset --asset native)
    --vault $(stellar contract id asset --asset native)
    --usdc $(stellar contract id asset --asset native)
    """
}

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]
# soroban-atomic-swap-contract = { id = "C123..." }
# soroban-auth-contract = { id = "C234..." }
# soroban-errors-contract = { id = "C345..." }
# soroban-hello-world-contract = { id = "C456..." }
# soroban-increment-contract = { id = "C567..." }
# soroban-token-contract = { id = "C678..." }
# eurc = { id = "C789..." }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# soroban-atomic-swap-contract = { id = "C987..." }
# soroban-auth-contract = { id = "C876..." }
# soroban-errors-contract = { id = "C765..." }
# soroban-hello-world-contract = { id = "C654..." }
# soroban-increment-contract = { id = "C543..." }
# soroban-token-contract = { id = "C432..." }
# eurc = { id = "C321..." }
