### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true

[[development.accounts]]
name = "me"
default = true

[development.contracts]
usdc_mock = { client = true, constructor_args = "--admin me --initial_supply 1000000000000000" }
rwa_invoices = { client = true, constructor_args = "--admin me --manager me --initial_supply 1000000000000000000" }
rwa_tbills = { client = true, constructor_args = "--admin me --manager me --initial_supply 1000000000000000000" }
rwa_realestate = { client = true, constructor_args = "--admin me --manager me --initial_supply 1000000000000000000" }
strwa_invoices = { client = true, constructor_args = "--admin me" }
strwa_tbills = { client = true, constructor_args = "--admin me" }
strwa_realestate = { client = true, constructor_args = "--admin me" }
vault_invoices = { client = true, constructor_args = "--admin me --rwa_token rwa_invoices --strwa_token strwa_invoices" }
vault_tbills = { client = true, constructor_args = "--admin me --rwa_token rwa_tbills --strwa_token strwa_tbills" }
vault_realestate = { client = true, constructor_args = "--admin me --rwa_token rwa_realestate --strwa_token strwa_realestate" }
mock_oracle = { client = true, constructor_args = "--bot_address me" }
lending_pool = { client = true, constructor_args = "--admin me --oracle mock_oracle --usdc usdc_mock" }

### Testnet environment configuration
[testnet.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[testnet.accounts]]
name = "testnet-deployer"
default = true

[testnet.contracts]
usdc_mock = { client = true }
rwa_invoices = { client = true }
rwa_tbills = { client = true }
rwa_realestate = { client = true }
strwa_invoices = { client = true }
strwa_tbills = { client = true }
strwa_realestate = { client = true }
vault_invoices = { client = true }
vault_tbills = { client = true }
vault_realestate = { client = true }
lending_pool = { client = true }
mock_oracle = { client = true }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
