### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true

[[development.accounts]]
name = "me"
default = true

[development.contracts]
usdc_mock = { client = true, constructor_args = "--admin me --initial_supply 1000000000000000" }
mock_rwa_token = { client = true, constructor_args = "--admin me --manager me --initial_supply 1000000000000000000" }
strwa_token = { client = true, constructor_args = "--admin me" }
rwa_vault = { client = true, constructor_args = "--admin me --rwa_token mock_rwa_token --strwa_token strwa_token" }
mock_oracle = { client = true, constructor_args = "--bot_address me" }
lending_pool = { client = true, constructor_args = "--admin me --oracle mock_oracle --vault rwa_vault --usdc usdc_mock" }

### Testnet environment configuration
[testnet.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[testnet.accounts]]
name = "testnet-deployer"
default = true

[testnet.contracts]
usdc_mock = { client = true }
mock_rwa_token = { client = true }
strwa_token = { client = true }
rwa_vault = { client = true }
mock_oracle = { client = true }
lending_pool = { client = true }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
